# Generated by Django 4.2.4 on 2023-09-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazesh', '0002_alter_mobile_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='price_diff_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
