# Generated by Django 4.2.4 on 2023-09-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazesh', '0007_alter_mobile_mobile_digi_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='brand',
            name='price_change_time',
            field=models.DateTimeField(null=True, verbose_name='تاریخ و ساعت ایجاد'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='price_change_time',
            field=models.DateTimeField(null=True, verbose_name='تاریخ و ساعت ایجاد'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='mobile_digi_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آیدی گوشی مناسب هر سایت'),
        ),
    ]
