"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from kombu import Queue
from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lk@qe&!!_mtj_vcmp&mz$o8=ny9x&chty=n@bbfmh*!mur8y_b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'rest_framework',
    'rest_framework_simplejwt',
    'khazesh',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        }
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'postgres',
#         'USER': 'postgres',
#         'PASSWORD': 'My:s3Cr3t/',
#         'HOST': '0.0.0.0',
#         'PORT': '',
#     }
# }

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': 'scraping_db',
         'USER': 'scraping',
         'PASSWORD': 'Ww0ygcseN,40!oXz',
         'HOST': 'localhost',
         'PORT': '',
         'OPTIONS': {
             'charset': 'utf8mb4',
         },
     }
}
# DATABASES = {
#      'default': {
#          'ENGINE': 'django.db.backends.mysql',
#          'NAME': 'scraping',
#          'USER': 'root',
#          'PASSWORD': '',
#          'HOST': 'localhost',
#          'PORT': '',
#          'OPTIONS': {
#              'charset': 'utf8mb4',
#          },
#      }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = "Asia/Tehran"
USE_I18N = True

USE_TZ = True


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_VERSION = '1.0'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LOGIN_REDIRECT_URL ='/search'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30*365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30*365),
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    # 'SIGNING_KEY': settings.SECRET_KEY,

}

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ALWAYS_EAGER = False
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_CHORD_PROPAGATES = False





# -------------------------
# Queues
# -------------------------
CELERY_QUEUES = (
    Queue("mobile_crawler_queue", routing_key="mobile_crawler"),
    Queue("laptop_crawler_queue", routing_key="laptop_crawler"),
    Queue("tablet_crawler_queue", routing_key="tablet_crawler"),
    Queue("watch_crawler_queue", routing_key="watch_crawler"),
    Queue("handsfree_crawler_queue", routing_key="handsfree_crawler"),
    Queue("powerbank_crawler_queue", routing_key="powerbank_crawler"),
    Queue("charger_crawler_queue", routing_key="charger_crawler"),
    Queue("speaker_crawler_queue", routing_key="speaker_crawler"),
)

# -------------------------
# Routes
# -------------------------
CELERY_ROUTES = {
    "khazesh.tasks.task_chain_crawls.start_mobile_crawlers": {
        "queue": "mobile_crawler_queue",
        "routing_key": "mobile_crawler"
    },
    "khazesh.tasks.task_chain_crawls.start_laptop_crawlers": {
        "queue": "laptop_crawler_queue",
        "routing_key": "laptop_crawler"
    },
    "khazesh.tasks.task_chain_crawls.start_tablet_crawlers": {
        "queue": "tablet_crawler_queue",
        "routing_key": "tablet_crawler"
    },
    "khazesh.tasks.task_chain_crawls.start_watch_crawlers": {
        "queue": "watch_crawler_queue",
        "routing_key": "watch_crawler"
    },
    "khazesh.tasks.task_chain_crawls.start_handsfree_crawlers": {
        "queue": "handsfree_crawler_queue",
        "routing_key": "handsfree_crawler"
    },
    "khazesh.tasks.task_chain_crawls.start_powerbank_crawlers": {
        "queue": "powerbank_crawler_queue",
        "routing_key": "powerbank_crawler"
    },
    "khazesh.tasks.task_chain_crawls.start_charger_crawlers": {
        "queue": "charger_crawler_queue",
        "routing_key": "charger_crawler"
    },
    "khazesh.tasks.task_chain_crawls.start_speaker_crawlers": {
        "queue": "speaker_crawler_queue",
        "routing_key": "speaker_crawler"
    },
}

# -------------------------
# Beat Schedule
# -------------------------
CELERY_BEAT_SCHEDULE = {
    # Mobile
    "start_mobile_crawler": {
        "task": "khazesh.tasks.task_chain_crawls.start_mobile_crawlers",
        "schedule": crontab(minute="*/15"),  
        "options": {"queue": "mobile_crawler_queue"},
    },
    # Laptop
    "start_laptop_crawler": {
        "task": "khazesh.tasks.task_chain_crawls.start_laptop_crawlers",
        "schedule": crontab(minute="*/30"), 
        "options": {"queue": "laptop_crawler_queue"},
    },
    # Tablet
    "start_tablet_crawler": {
        "task": "khazesh.tasks.task_chain_crawls.start_tablet_crawlers",
        "schedule": crontab(minute="*/15"), 
        "options": {"queue": "tablet_crawler_queue"},
    },
    # Watch
    "start_watch_crawler": {
        "task": "khazesh.tasks.task_chain_crawls.start_watch_crawlers",
        "schedule": crontab(minute="*/45"), 
        "options": {"queue": "watch_crawler_queue"},
    },
    # Handsfree
    "start_handsfree_crawler": {
        "task": "khazesh.tasks.task_chain_crawls.start_handsfree_crawlers",
        "schedule": crontab(minute="*/45"),  
        "options": {"queue": "handsfree_crawler_queue"},
    },
    # Powerbank
    "start_powerbank_crawler": {
        "task": "khazesh.tasks.task_chain_crawls.start_powerbank_crawlers",
        "schedule": crontab(minute="*/45"),  
        "options": {"queue": "powerbank_crawler_queue"},
    },
    # Charger
    "start_charger_crawler": {
        "task": "khazesh.tasks.task_chain_crawls.start_charger_crawlers",
        "schedule": crontab(minute="*/45"),  
        "options": {"queue": "charger_crawler_queue"},
    },
    # Speaker
    "start_speaker_crawler": {
        "task": "khazesh.tasks.task_chain_crawls.start_speaker_crawlers",
        "schedule": crontab(minute="*/45"), 
        "options": {"queue": "speaker_crawler_queue"},
    },
}