# Generated by Django 4.2.4 on 2023-09-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ و ساعت آپدیت')),
                ('name', models.CharField(max_length=50, verbose_name='برند')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ و ساعت آپدیت')),
                ('mobile_digi_id', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=50, verbose_name='مدل')),
                ('color_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='رنگ')),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True, verbose_name='کد هگز رنگ')),
                ('seller', models.CharField(blank=True, max_length=100, null=True, verbose_name='فروشنده')),
                ('guarantee', models.CharField(blank=True, max_length=150, null=True, verbose_name='گارانتی')),
                ('ram', models.CharField(blank=True, max_length=20, null=True, verbose_name='حافظه رم')),
                ('memory', models.CharField(blank=True, max_length=20, null=True, verbose_name='حافظه داخلی')),
                ('vietnam', models.BooleanField(blank=True, default=False, null=True, verbose_name='ساخت ویتنام')),
                ('dual_sim', models.BooleanField(default=True, verbose_name='دو سیم کارت')),
                ('title', models.CharField(max_length=200, verbose_name='توضیحات تایتل')),
                ('max_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='بیشترین قیمت')),
                ('min_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='کمترین قیمت')),
                ('old_min_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='کمترین قیمت قبلی')),
                ('active', models.BooleanField(default=True, verbose_name='موجود')),
                ('site', models.CharField(max_length=30, verbose_name='سایت')),
                ('url', models.URLField()),
                ('not_active', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobiles', to='khazesh.brand', verbose_name='برند')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
