# Generated by Django 4.2.4 on 2023-09-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazesh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='model',
            field=models.CharField(max_length=100, verbose_name='مدل'),
        ),
    ]
