# Generated by Django 4.2.4 on 2023-09-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazesh', '0003_mobile_price_diff_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='price_diff_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
