# Generated by Django 4.2.4 on 2023-09-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazesh', '0005_alter_mobile_mobile_digi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
