# Generated by Django 4.2.4 on 2023-09-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazesh', '0006_alter_mobile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobile_digi_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
