# Generated by Django 3.2 on 2024-05-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazesh', '0009_remove_brand_price_change_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
