# Generated by Django 3.2 on 2024-05-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazesh', '0010_mobile_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='تاریخ و ساعت آپدیت'),
        ),
    ]
