# Generated by Django 5.0.6 on 2024-09-09 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazesh', '0012_connectionerrorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecutionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('last_executed', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
