# Generated by Django 5.0.6 on 2024-12-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazesh', '0013_codeexecutionstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='color_hex',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='کد هگز رنگ'),
        ),
    ]
