# Generated by Django 4.0.7 on 2025-03-28 01:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('khazesh', '0014_alter_mobile_color_hex'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=50, verbose_name='نام فارسی برند ')),
                ('name_en', models.CharField(max_length=50, verbose_name='نام لاتین برند')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=50, verbose_name='نام فارسی دسته بندی')),
                ('name_en', models.CharField(max_length=50, verbose_name='نام لاتین دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='مدل')),
                ('color_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='رنگ')),
                ('color_hex', models.CharField(blank=True, max_length=500, null=True, verbose_name='کد هگز رنگ')),
                ('seller', models.CharField(blank=True, max_length=100, null=True, verbose_name='فروشنده')),
                ('guarantee', models.CharField(blank=True, max_length=150, null=True, verbose_name='گارانتی')),
                ('title', models.CharField(max_length=200, verbose_name='توضیحات تایتل')),
                ('max_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='بیشترین قیمت')),
                ('min_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='کمترین قیمت')),
                ('old_min_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='کمترین قیمت قبلی')),
                ('stock', models.BooleanField(default=True, verbose_name='موجود')),
                ('fake', models.BooleanField(default=True, verbose_name='اصل یا غیراصل')),
                ('site', models.CharField(max_length=30, verbose_name='سایت')),
                ('url', models.URLField(max_length=1000)),
                ('price_change_time', models.DateTimeField(null=True, verbose_name='تاریخ و ساعت ایجاد')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='تاریخ و ساعت آپدیت')),
                ('price_diff_time', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_bartardigital', models.DateTimeField(null=True, verbose_name='آخرین بروزرسانی در برتردیجیتال')),
                ('description', models.CharField(blank=True, max_length=10000, null=True, verbose_name='توضیحات تکمیلی')),
                ('custom_id', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khazesh.brandaccessories', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khazesh.categoryaccessories', verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='CodeExecutionStateAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('last_executed', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khazesh.categoryaccessories', verbose_name='دسته بندی')),
            ],
        ),
    ]
