# Generated by Django 4.0.7 on 2025-09-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazesh', '0016_brandlaptop_categorylaptop_mobile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobile_digi_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='آیدی گوشی مناسب هر سایت'),
        ),
    ]
